<?php
/**
 * 基础类
 */

namespace app\common\controller;
use think\Db;
use think\Controller;
class Base extends Controller
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}